### ISSUE TITLE
webilder doesn't load with ubuntu natty 11.04

### ISSUE THREAD

**Issue by bhupi** [thesamet/webilder#19]
I upgraded to natty 11.04 this morning.  First thing I did was go back to using gnome desktop rather than the new desktop environment.  When gnome desktop loaded I got a pop-up saying that webilder couldn't load.  I am running with the latest version of webilder.  When I try to run webilder_desktop from the command line I get:

webilder_desktop
Traceback (most recent call last):
  File "/usr/local/bin/webilder_desktop", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2671, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Webilder==0.7

I tried to install all of the recommended packages for ubuntu from webilder website and it appears that I have all of the necessary packages installed.  I tried to do a fresh install of webilder and get the message: Dependency is not satisfiable: python-gnome2-desktop

**Comment by borisdayma** [comment]
It doesn't work either with unity interface

**Comment by thesamet** [comment]
I've added initial support for Webilder under Unity in Ubuntu Natty. Can you test and send your comments:

To try it out, type the following in a command line terminal:

git clone git://github.com/thesamet/webilder.git
cd webilder
sudo python setup.py install --install-data=/usr
webilder_unity_indicator

-Nadav

**Comment by bhupi** [comment]
It does now startup and display photos!  I am running with Unity and not Gnome.  I noticed that when I chose browse photos and went into the GUI I could not see the thumbnails under many of my directories that I have pictures stored.  These did work before with the older version of webilder/ubuntu.  Some folders load fine and some don't.  After I click on the directory containing the photos, I see this error in the screen where I issued the command:  webilder_unity_indicator:
[Errno 2] No such file or directory: '/desktop/Webilder-Photos/Digital Art/wallpaper-248889.inf'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webilder/WebilderDesktop.py", line 106, in on_tree_handle_selection_changed
    self.load_directory_collection(rootdir)
  File "/usr/local/lib/python2.7/dist-packages/webilder/WebilderDesktop.py", line 115, in load_directory_collection
    self.load_collection(images, monitor_dir=dirname)
  File "/usr/local/lib/python2.7/dist-packages/webilder/WebilderDesktop.py", line 142, in load_collection
    basename)+'.inf')
  File "/usr/local/lib/python2.7/dist-packages/webilder/infofile.py", line 17, in parse_info_file
    fileobj.close()
UnboundLocalError: local variable 'fileobj' referenced before assignment

I don't see any photos under the directories where I am getting the above error.  

Thanks for your work on this.  At least it us up and running now.  Let me know if you need any more info.  I really like your program, it is my favorite for displaying wallpapers..

**Comment by thesamet** [comment]
@bhupi thanks for reporting this! This bug sneaked in recently. I believe I fixed it -- can you pull again and report?

**Comment by bhupi** [comment]
Yes, I can now see/display all of my photo collection.  Thanks.  But now I found a new problem.   I am finding that after I reboot webilder does not start.  We I try to start it I see:

webilder_unity_indicator 
[1] 4425
laptop17:/usr/local/bin$ Traceback (most recent call last):
  File "./webilder_unity_indicator", line 9, in <module>
    load_entry_point('Webilder==0.7', 'console_scripts', 'webilder_unity_indicator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1954, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/webilder/webilder_unity_indicator.py", line 14, in <module>
    from webilder.base_applet import BaseApplet
  File "/usr/local/lib/python2.7/dist-packages/webilder/base_applet.py", line 11, in <module>
    from webilder.config import config, set_wallpaper, reload_config
  File "/usr/local/lib/python2.7/dist-packages/webilder/config.py", line 126, in <module>
    config = ConfigObject(DEFAULT_CONFIG_FILE)  # pylint: disable=C0103
  File "/usr/local/lib/python2.7/dist-packages/webilder/config.py", line 34, in **init**
    raise ValueError, _("collection.dir is set to a non-directory, "
ValueError: collection.dir is set to a non-directory, check your config file.

[1]+  Exit 1                  webilder_unity_indicator

I noticed the last line says "collection.dir" is not set.  Mine is set to:  collection.dir = '/desktop/Webilder-Photos' 
I tried removing the quotes on /desktop/Webilder-Photos and saved the file, restarted, still didn't work.  I put the quotes back in, so the file was like it originally was, saved the file, restarted and it now runs.   Makes no sense to me.
It is running, I just have to tweak my config file after I reboot.

**Comment by bhupi** [comment]
Hmm, well it looks like I am seeing another problem.  When I click on the webilder icon on the unity bar I don't get the pulldown menu so I can't run the GUI or change the picture.  The icon is highlighted with a tiny border around it but nothing happens.   I tried restarting webilder but am still having the problem.

**Comment by bhupi** [comment]
That is the webilder icon on the unity panel, the top panel, not to be confused with the unity sidebar on the left.

**Comment by bhupi** [comment]
Back again.. ;)  Well I guess it was me with the webilder icon problem.  I noticed after starting and stopping webilder some more that when I started webilder, the icon on the unity panel was highlighted.  When I clicked on it nothing happened.  I found that if I clicked on something else on the unity panel, and then clicked back on the webilder icon I can now get the pulldown menu.  Don't know if that is a bug or not.  I now am not seeing any problems after stopping/restarting.  So I am not sure what caused the problem.

**Comment by thesamet** [comment]
Ok, thanks for reporting. In the current version of the code, webilder does not automatically starts when you login. I'll fix this soon. I'll look into what possibly can cause the highlighting/irresponsiveness when it starts.

**Comment by bhupi** [comment]
Here is something else.  I can't delete any photos.  I get this error when I try:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/webilder/WebilderDesktop.py", line 421, in on_delete_images_handle_activate
    delete_files(self.main_window, forever=False)
  File "/usr/local/lib/python2.7/dist-packages/webilder/WebilderDesktop.py", line 451, in delete_files
    gnomevfs.monitor_cancel(monitor['monitor'])
ValueError: Invalid monitor id

**Comment by thesamet** [comment]
Thanks for reporting the image deletion bug as well. This should be fixed now.

**Comment by ghost** [comment]
A Follow-up. I cannot get the Unity Applet to load automatically either. If I open a terminal and run it from there it loads as long as that terminal window is open. Switching my login session to "Classic Ubuntu" has the regular Gnome applet working fine. Anything I can help with as a user, not coder? Using Ubuntu Natty 64Bit.

**Comment by thesamet** [comment]
I've released v 0.7.1 today that fixes the autostart issue.

**Comment by bhupi** [comment]
I installed the new version and all is well.  It now runs on boot-up.  Thanks for your work on this.

**Comment by ghost** [comment]
I've also installed the new version and everything works fine. Only issue I had was with installation. I had to remove the previous version first, it wouldn't just upgrade.
